version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: geochangesdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  kartverketapplikasjon:   
    image: ${DOCKER_REGISTRY-}kartverketapplikasjon
    build:
      context: .
      dockerfile: KartverketApplikasjon/Dockerfile
    ports:
      - "5001:8081"
    depends_on:
      - mariadb
    environment:
      - ConnectionStrings__DefaultConnection=Server=mariadb;Database=geochangesdb;User=root;Password=123
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend: